Feature/printscreen
fyne-io/fynedesk pull request #141
Opened 2020-10-19 08:37 UTC by andydotxyz

Add print screen features
* PrintScreen button captures all displays
* Shift+PrintScreen captures the current window with border.

The images are generated in the windowmanager code but our UI overlay then presents it to the user and offers to save.

2020-10-19 10:31 UTC, Jacalz reviewed
This is a great feature. I do have some issues with Fynedesk crashing when I try to take a screenshot of GTK apps like Firefox and it seems like capturing GTK apps doesn't work in full screen mode either.
![firefox-empty](https://user-images.githubusercontent.com/25466657/96438745-d8b86900-1206-11eb-8ffe-d3908aff287f.png)

2020-10-19 12:14 UTC, andydotxyz commented
From your screenshot it's hard to say what should have been shown - was firefox full screen on the left window?

2020-10-19 12:27 UTC, Jacalz commented
Yeah that is a very true point. It was not full-screen, I think, but I do know that I tested Nautilus (the standard gnome file-manager) and it did not show either. Please also notice that the borders on `wormhole-gui` are gone.

2020-10-21 08:50 UTC, andydotxyz commented
@Jacalz thinking more about this the missing borders were fixed in one of the later commits in this PR - can you please double check that you were testing against the latest version of this PR?

It is possibly still an issue for other reasons, but one issue was resolved during development :)

2020-10-21 08:51 UTC, andydotxyz commented
And to confirm, when your windows are missing they are leaving those white rectangles rather than being omitted completely?

2020-10-21 18:48 UTC, Jacalz commented
@andydotxyz I updated to the latest version and it appears to still be the case that borders are not shown. They do appear as dark in the preview for the screenshot though. Perhaps they are transparent? Yup, double checked in GIMP and they are indeed transparent.
![image](https://user-images.githubusercontent.com/25466657/96768347-115e6b00-13de-11eb-8623-762cca44b102.png)

Yes, the gtk windows are replaced with the white rectangles. I have never seen any windows be left out entirely. Please see the attached screenshot below:
![firefox-empty](https://user-images.githubusercontent.com/25466657/96768083-b298f180-13dd-11eb-9a45-cec3cfc1a58a.png)

Aspect ratio for the screenshot viewer seems to be wrong until it gets some sort of response (click, drag or something that triggers a refresh) and then it gets the right aspect ratio.
![strange-aspect](https://user-images.githubusercontent.com/25466657/96768778-8762d200-13de-11eb-9017-80f50445c7a2.png)

I have also been seeing once in a while that the screenshot viewer will not show any picture after taking a screenshot. I cannot replicate it reliably but have seen it once or twice at least.

2020-10-21 19:07 UTC, andydotxyz commented
Thanks. The aspect issues were resolved in Fyne earlier today, and should be OK now.
I will try to replicate the GTK issues later tonight

2020-10-22 18:28 UTC, andydotxyz commented
Strange, here is nautilus at my end...
![nautilus](https://user-images.githubusercontent.com/294436/96914249-a9bb2500-149c-11eb-9775-205826988f10.png)

2020-10-22 18:29 UTC, andydotxyz commented
Firefox worked too...
![firefox](https://user-images.githubusercontent.com/294436/96914399-db33f080-149c-11eb-8192-6d433fceb4fa.png)

2020-11-19 10:00 UTC, andydotxyz commented
Perhaps the issue @Jacalz finds is due to screen depth not matching the colour depth on the borders?
Can you share anything about the colour confugration in your Xorg @Jacalz.

Have you been able to test this yet @okratitan - it's been sitting for a month now and I'd like to gauge whether I am lucky in this working for me, or unlucky that it doesn't work on some old configuration...

2020-11-22 17:23 UTC, Jacalz commented
@andydotxyz Sorry, but I am not entireley sure where to look for that sort of colour information. Do you perhaps know where that information is usually stored?

2020-11-22 18:09 UTC, andydotxyz commented
It might be determined at runtime - but some X summary printout or maybe xrandr could list it?

2020-12-09 15:39 UTC, Jacalz commented
Looks like I still have the same issues with windows being blank (transparent). Also does look like it can't capture the second monitor at all after the multidesk fix.

2020-12-11 19:01 UTC, Jacalz commented
![fynedesk-printscreen](https://user-images.githubusercontent.com/25466657/101943496-79b21780-3beb-11eb-943c-6673b99fb5ae.png)
This is what I am seeing on the latest commit. Everything that isn't a fyne application is transparent and the second monitor is not captured at all.

2020-12-15 16:51 UTC, Jacalz requested changes
Thanks for the latest fix. Screenshots are now working :1st_place_medal: 
Just two smaller issues, but otherwise approved :+1:

2020-12-15 16:51 UTC, Jacalz commented on internal/ui/screenshot.go
> +		if err != nil {
You are not checking if `write == nil`. I was noticing that pressing save and then cancelling crashes the desktop.

2020-12-15 16:51 UTC, Jacalz commented on internal/ui/screenshot.go
> +	w.Resize(fyne.NewSize(400, 250))
Could we perhaps make the window slightly larger? The window is too small to make the save dialog big enough to use.

2020-12-15 19:24 UTC, Jacalz approved these changes
Looks good to me. Staticcheck is failing, so you might need to manually merge this.

2020-12-15 21:06 UTC, merged